server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:classpath:secret.yaml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/oauth_module}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID:}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:}
            scope: openid,profile,email
            redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/google}
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID:}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI:{baseUrl}/login/oauth2/code/kakao}
            scope: profile_nickname,account_email
          naver:
            client-id: ${OAUTH_NAVER_CLIENT_ID:}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH_NAVER_REDIRECT_URI:{baseUrl}/login/oauth2/code/naver}
            scope: name,email
          apple:
            client-id: ${OAUTH_APPLE_CLIENT_ID:}
            client-secret: ${OAUTH_APPLE_CLIENT_SECRET:}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH_APPLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/apple}
            scope: name,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: sub

logging:
  level:
    org.springframework.security: INFO

jwt:
  secret: ${JWT_SECRET:change-me-to-a-long-secret-key-please}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_TTL:900}
  refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_TTL:1209600}
